//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crawler.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crawler.UnitTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html lang=&quot;ru&quot; xml:lang=&quot;ru&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:Web=&quot;http://schemas.live.com/Web/&quot;&gt;&lt;script type=&quot;text/javascript&quot;&gt;//&lt;![CDATA[
        ///si_ST=new Date;
        /////]]&gt;&lt;/script&gt;&lt;head&gt;&lt;!--pc--&gt;&lt;title&gt;html5 - Bing&lt;/title&gt;&lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;content-type&quot; /&gt;&lt;meta name=&quot;referrer&quot; content=&quot;origin&quot; /&gt;&lt;link href=&quot;/search?format=rss&amp;amp;q=html5&amp;amp;cc=ru&quot; rel=&quot;alternate&quot; title=&quot;XML&quot; type=&quot;text/xml&quot; /&gt;&lt;link href=&quot;/search?format=rss&amp;amp;q=html5&amp;amp;cc=ru&quot; rel=&quot;alt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BingPage {
            get {
                return ResourceManager.GetString("BingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;&lt;html itemscope=&quot;&quot; itemtype=&quot;http://schema.org/SearchResultsPage&quot; lang=&quot;ru&quot;&gt;&lt;head&gt;&lt;meta content=&quot;text/html; charset=UTF-8&quot; http-equiv=&quot;Content-Type&quot;&gt;&lt;meta content=&quot;/images/branding/googleg/1x/googleg_standard_color_128dp.png&quot; itemprop=&quot;image&quot;&gt;&lt;link href=&quot;/images/branding/product/ico/googleg_lodp.ico&quot; rel=&quot;shortcut icon&quot;&gt;&lt;noscript&gt;&lt;meta content=&quot;0;url=/search?q=sports&amp;amp;newwindow=1&amp;amp;ie=UTF-8&amp;amp;gbv=1&amp;amp;sei=wB_XV8GvNOug6ASn_JeoBA&quot; http-equiv=&quot;refresh&quot;&gt;&lt;style&gt;table,div,span,p{display:non [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GooglePage {
            get {
                return ResourceManager.GetString("GooglePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html class=&quot;i-ua_js_no i-ua_css_standard&quot; lang=&quot;ru&quot;&gt;&lt;head&gt;&lt;meta charset=&quot;utf-8&quot;/&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;&lt;title&gt;Яндекс&lt;/title&gt;&lt;script&gt;;(function(d,e,c,r){e=d.documentElement;c=&quot;className&quot;;r=&quot;replace&quot;;e[c]=e[c][r](&quot;i-ua_js_no&quot;,&quot;i-ua_js_yes&quot;);if(d.compatMode!=&quot;CSS1Compat&quot;)e[c]=e[c][r](&quot;i-ua_css_standart&quot;,&quot;i-ua_css_quirks&quot;)})(document);;(function(d,e,c,n,w,v,f){e=d.documentElement;c=&quot;className&quot;;n=&quot;createElementNS&quot;;f=&quot;firstChild&quot;;w=&quot;http://www.w3.org/2000/svg&quot;;e[c]+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YandexPage {
            get {
                return ResourceManager.GetString("YandexPage", resourceCulture);
            }
        }
    }
}
